#!/bin/sh

set -e
# first arg is `-f` or `--some-option`

if [ "${1#-}" != "$1" ]; then

	set -- apache2-foreground "$@"

fi

createconf() {
  customer_config.sh
  config_db.sh
  if [ ! -d /var/conf/themes ]
  then
    mkdir -p /var/conf/themes
    cp -r  /var/www/html/testlink/gui/themes/* /var/conf/themes
  fi

  if [  -d /var/www/html/testlink/install ]
  then
    mv /var/www/html/testlink/install /var/www/html/testlink/installed
  fi


}

echo "Configurando testlink"

createconf

echo "Ejecutando $@"
exec "$@"
